services:
  mt5-server:
    image: jerry/mt5-custom:v1
    container_name: mt5-server
    environment:
      - VNC_PWD=jerry1234
    volumes:
      # 配置與腳本目錄
      - .:/mt5docker
      # MT5 可攜式設定檔持久化（AppData）
      - "./MT5_Data:/opt/wineprefix/drive_c/users/root/AppData/Roaming/MetaTrader 5"
    entrypoint: /mt5docker/start_server.sh
    ports:
      - 5901:5901
      - 6081:6081
      - 8001:8001
    restart: always

  python-runner:
    image: jerry/mt5-custom:v1
    container_name: python-runner
    volumes:
      # 將整個專案代碼映射到 /app
      - ..:/app
    ports:
      - "0.0.0.0:8090:8090"
    entrypoint: /app/mt5docker/start_runner.sh
    depends_on:
      - mt5-server
    restart: always
